# SQLite version 3.x
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'
#
default: &default
  #adapter: postgresql
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  #  database: xavy_development

test:
  <<: *default
  database: db/test.sqlite3
  #  database: xavy_test

production:
  <<: *default
  database: db/production.sqlite3
#  adapter: postgresql
#  encoding: unicode
#  username: xavy
#  password: <%= ENV['XAVY_DATABASE_PASSWORD'] %>
#  pool: 5
